{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    event homeTeam standardPoint awayTeam gameType winDistribute  \\\n",
      "0     EPL    본머스             NaN     크리스털       일반         승2.65   \n",
      "1     EPL    본머스          H +1.0     크리스털      핸디캡         승1.47   \n",
      "2     EPL    본머스         U/O 2.5     크리스털     언더오버         U1.60   \n",
      "3     EPL   풀럼               NaN     사우샘프       일반         승1.73   \n",
      "4     EPL   풀럼            H -1.0     사우샘프      핸디캡         승2.95   \n",
      "..    ...      ...           ...      ...      ...           ...   \n",
      "136   NBA     덴버너게        H +3.5     보스셀틱      핸디캡         승1.76   \n",
      "137   NBA     덴버너게     U/O 235.5     보스셀틱     언더오버         U1.74   \n",
      "138   A리그     웰링피닉           NaN     멜버시티       일반         승3.15   \n",
      "139   A리그     웰링피닉        H +1.0     멜버시티      핸디캡         승1.75   \n",
      "140   A리그     웰링피닉       U/O 2.5     멜버시티     언더오버         U2.07   \n",
      "\n",
      "    drawDistribute loseDistribute   finalScore gameResult  \n",
      "0            무2.95          패2.38        0 : 2          패  \n",
      "1            무3.90          패5.00        1 : 2          패  \n",
      "2                -          O1.96            2          U  \n",
      "3            무3.40          패3.80        2 : 1          승  \n",
      "4            무3.50          패1.95        1 : 1          무  \n",
      "..             ...            ...          ...        ...  \n",
      "136              -          패1.76  126.5 : 111          승  \n",
      "137              -          O1.78          234          U  \n",
      "138          무3.45          패1.89        1 : 3          패  \n",
      "139          무3.75          패3.35        2 : 3          패  \n",
      "140              -          O1.53            4          O  \n",
      "\n",
      "[141 rows x 10 columns]\n",
      "\n",
      "\n",
      "\u001b[1m> Entering new AgentExecutor chain...\u001b[0m\n",
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3526, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\Administrator\\AppData\\Local\\Temp\\ipykernel_29024\\3497004631.py\", line 17, in <module>\n",
      "    agent.run('데이터의 행과 열의 갯수는 어떻게 돼?')\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chains\\base.py\", line 505, in run\n",
      "    if len(args) != 1:\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chains\\base.py\", line 310, in __call__\n",
      "    except BaseException as e:\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chains\\base.py\", line 304, in __call__\n",
      "    try:\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\agents\\agent.py\", line 1146, in _call\n",
      "    \"available_tool_names\": list(name_to_tool_map.keys()),\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\agents\\agent.py\", line 933, in _take_next_step\n",
      "    )\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\agents\\openai_functions_agent\\base.py\", line 104, in plan\n",
      "    functions=self.functions,\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\base.py\", line 653, in predict_messages\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\base.py\", line 600, in __call__\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\base.py\", line 349, in generate\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\base.py\", line 339, in generate\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\base.py\", line 492, in _generate_with_cache\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\openai.py\", line 412, in _generate\n",
      "    **kwargs: Any,\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\openai.py\", line 342, in completion_with_retry\n",
      "    \"\"\"Use tenacity to retry the completion call.\"\"\"\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\tenacity\\__init__.py\", line 289, in wrapped_f\n",
      "    return self(f, *args, **kw)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\tenacity\\__init__.py\", line 379, in __call__\n",
      "    do = self.iter(retry_state=retry_state)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\tenacity\\__init__.py\", line 314, in iter\n",
      "    return fut.result()\n",
      "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\concurrent\\futures\\_base.py\", line 438, in result\n",
      "    return self.__get_result()\n",
      "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\concurrent\\futures\\_base.py\", line 390, in __get_result\n",
      "    raise self._exception\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\tenacity\\__init__.py\", line 382, in __call__\n",
      "    result = fn(*args, **kwargs)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\langchain\\chat_models\\openai.py\", line 340, in _completion_with_retry\n",
      "    self, run_manager: Optional[CallbackManagerForLLMRun] = None, **kwargs: Any\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\openai\\api_resources\\chat_completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\openai\\api_requestor.py\", line 298, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\openai\\api_requestor.py\", line 700, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\openai\\api_requestor.py\", line 765, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.AuthenticationError: Incorrect API key provided: {OPENAI_****KEY}. You can find your API key at https://platform.openai.com/account/api-keys.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2120, in showtraceback\n",
      "    stb = self.InteractiveTB.structured_traceback(\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1435, in structured_traceback\n",
      "    return FormattedTB.structured_traceback(\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1326, in structured_traceback\n",
      "    return VerboseTB.structured_traceback(\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1173, in structured_traceback\n",
      "    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1088, in format_exception_as_a_whole\n",
      "    frames.append(self.format_record(record))\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 970, in format_record\n",
      "    frame_info.lines, Colors, self.has_colors, lvals\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 792, in lines\n",
      "    return self._sd.lines\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\stack_data\\utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\stack_data\\core.py\", line 734, in lines\n",
      "    pieces = self.included_pieces\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\stack_data\\utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\stack_data\\core.py\", line 681, in included_pieces\n",
      "    pos = scope_pieces.index(self.executing_piece)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\stack_data\\utils.py\", line 144, in cached_property_wrapper\n",
      "    value = obj.__dict__[self.func.__name__] = self.func(obj)\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\stack_data\\core.py\", line 660, in executing_piece\n",
      "    return only(\n",
      "  File \"c:\\Users\\Administrator\\Desktop\\공부\\ai_study\\env\\lib\\site-packages\\executing\\executing.py\", line 190, in only\n",
      "    raise NotOneValueFound('Expected one value, found 0')\n",
      "executing.executing.NotOneValueFound: Expected one value, found 0\n"
     ]
    }
   ],
   "source": [
    "from langchain.agents.agent_types import AgentType\n",
    "from langchain.chat_models import ChatOpenAI\n",
    "from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent\n",
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\"./230001data.csv\")\n",
    "df.head()\n",
    "print(df)\n",
    "\n",
    "agent = create_pandas_dataframe_agent(\n",
    "  ChatOpenAI(temperature=0),\n",
    "  df,\n",
    "  verbose=True,\n",
    "  agent_type=AgentType.OPENAI_FUNCTIONS,\n",
    ")\n",
    "\n",
    "agent.run('데이터의 행과 열의 갯수는 어떻게 돼?')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "env",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
